. "$HOME/.cargo/env"

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export NVM_DIR="$HOME/.nvm"

export KUBECTL_ZSH_COMPLETION_PATH=$HOME/.kubectl_zsh_completion # kubectl completionn

export LSCOLORS=Gxfxcxdxbxegedabagacad # https://geoff.greer.fm/lscolors/
