. "$HOME/.cargo/env"

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export NVM_DIR="$HOME/.nvm"

export PATH="$PATH:/opt/homebrew/opt/openssl@3/bin" # used by rbenv
export PATH="$PATH:$HOME/.rbenv/bin"

export KUBECTL_ZSH_COMPLETION_PATH=$HOME/.kubectl_zsh_completion # kubectl completionn

export LSCOLORS=Gxfxcxdxbxegedabagacad # https://geoff.greer.fm/lscolors/

export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/homebrew/opt/openssl@3/lib/pkgconfig:/opt/homebrew/opt/readline/lib/pkgconfig" # used by rbenv
