[[ ! -f $HOME/.cargo/env ]] || . "$HOME/.cargo/env"

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export NVM_DIR="$HOME/.nvm"

export PATH="$HOME/.rbenv/shims:${PATH}"

export KUBECTL_ZSH_COMPLETION_PATH=$HOME/.kubectl_zsh_completion # kubectl completionn

export LSCOLORS=Gxfxcxdxbxegedabagacad # https://geoff.greer.fm/lscolors/

export PNPM_HOME="$HOME/Library/pnpm"

export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

case ":${PATH}:" in
    # add binaries to PATH if they aren't added yet
    # affix colons on either side of $PATH to simplify matching
    # existing binaries
    #   - uv
    #   - uvx
  *:"$HOME/.local/bin":*)
    ;;
  *)
    # Prepending path in case a system-installed binary needs to be overridden
    export PATH="$HOME/.local/bin:$PATH"
    ;;
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
