# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# environment
export LSCOLORS=Gxfxcxdxbxegedabagacad # https://geoff.greer.fm/lscolors/
export GOPATH=$HOME/go

# aliases
alias v="nvim"
alias ls="ls -GH"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ga="git add"
alias gdf="git diff"
alias gst="git status"
alias gcmsg="git commit -m"
alias gco="git checkout"
alias gs="git switch"
alias gp="git push"
alias gpf="git push --force-with-lease"
function gpu ()
{
  branch="$(git branch --show-current)"
  [[ -z $branch ]] && return
  git push --set-upstream origin $branch
}

eval $(thefuck --alias)

# set PATH
export PATH=$PATH:$GOPATH/bin

# case insensitive tab completion
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
