eval "$(starship init zsh)"

source ~/.zsh_aliases
source ~/.zsh_completion

autoload -Uz compinit && compinit

if [ -f ~/.work_stuff.sh ]; then
  . ~/.work_stuff.sh
  source-kubectl-completion
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(zoxide init zsh --cmd j)"
